POSITION_BOSS = 'boss'
POSITION_VICE = 'vice'
POSITION_TREASURE = 'treasure'
POSITION_SECRET = 'secret'
POSITION_LIBRARY = 'library'
POSITION_FREE = 'free'
POSITION_COVISION = 'covision'

POSITIONS_BOARD = [
    POSITION_BOSS,
    POSITION_VICE,
    POSITION_TREASURE,
    POSITION_SECRET,
    POSITION_LIBRARY,
    POSITION_FREE,
]

POSITIONS_ALL = [
    POSITION_BOSS,
    POSITION_VICE,
    POSITION_TREASURE,
    POSITION_SECRET,
    POSITION_LIBRARY,
    POSITION_FREE,
    POSITION_COVISION,
]

FELLOW_ACTIVE = 'active'  # is active KMS fellow
FELLOW_FELLOW = 'fellow'  # is confirmed KMS fellow
FELLOW_BOARD = 'board'  # has access to KMS site admin panels

ELECTION_ACTIVE = 'active'
ELECTION_REGISTER = 'register'
ELECTION_VOTING = 'voting'

STAGE_BOSS = 'boss'
STAGE_BOARD = 'board'
STAGE_COVISION = 'covision'

ELECTION_STAGES = [
    STAGE_BOSS, 
    STAGE_BOARD, 
    STAGE_COVISION,
]

POSITIONS = {
    None:POSITIONS_ALL,
    STAGE_BOSS:[
        POSITION_BOSS,
      ],
    STAGE_BOARD:[
        POSITION_VICE,
        POSITION_TREASURE,
        POSITION_SECRET,
        POSITION_LIBRARY,
        POSITION_FREE,
      ],
    STAGE_COVISION:[
        POSITION_COVISION,
      ],
}

NEWS_FSZYSKO = 'fszysko'
NEWS_ANTEOMNIA = 'anteomnia'
NEWS_CONFERENCE = 'cnfrnce'
NEWS_PHOTO = 'fotki'
NEWS_WYCINEK = 'wycinek'
NEWS_ALL = 'all'

FEATURE_DEMO = 'demo'
FEATURE_DIKE_CANDIDATE_BOARD_COVISION_CONFLICT_FORBIDDEN = 'dike_candidate_board_covision_conflict_forbidden'
FEATURE_EMAIL_VERIFICATION = 'email_verification'
FEATURE_MULTITHREADING = 'multithreading'
FEATURE_STV_REJECTION = 'stv_rejection'
