POSITION_BOSS = 'boss'
POSITION_VICE = 'vice'
POSITION_TREASURE = 'treasure'
POSITION_SECRET = 'secret'
POSITION_LIBRARY = 'library'
POSITION_FREE = 'free'
POSITION_COVISION = 'covision'

POSITIONS_BOARD = {
    POSITION_BOSS,
    POSITION_VICE,
    POSITION_TREASURE,
    POSITION_SECRET,
    POSITION_LIBRARY,
    POSITION_FREE,
}

POSITIONS_ALL = {
    POSITION_BOSS,
    POSITION_VICE,
    POSITION_TREASURE,
    POSITION_SECRET,
    POSITION_LIBRARY,
    POSITION_FREE,
    POSITION_COVISION,
}
